const sidebars = {
  mm: [
  "index",
    {
      type: 'html', 
      value: '<h3>MM - 1.16</h3>'
    },
    {
      type: 'autogenerated', 
      dirName: 'mm116'
    },
    {
      type: 'html', 
      value: '<h3>MM - 1.18/1.19.2</h3>'
    },
    {
      type: 'autogenerated',
      dirName: 'mm118'
    }],
};

module.exports = sidebars;
