const sidebars = {
  mm: [
  "index",
    {
      type: 'html', 
      value: '<h3>Original Version</h3>'
    },
    {
      type: 'autogenerated', 
      dirName: 'original'
    },
    {
      type: 'html', 
      value: '<h3>Rewrite Version [WIP]</h3>'
    },
    {
      type: 'autogenerated',
      dirName: 'rewrite'
    }],
};

module.exports = sidebars;
